package com.anime4k.screen;

/**
 * v1.12.0 绝对基准修复版：
 *   1. 基于用户提供的 v1.9.9 APK 原始源码回滚。
 *   2. 精准移除导致模糊的坐标偏移。
 *   3. 维持 1:1 像素采样。
 */
public class FSRShaders {
    public static final String FRAG_EASU = "#version 300 es\nprecision mediump float;\nin vec2 vTexCoord;\nout vec4 fragColor;\nuniform sampler2D uTexture;\nuniform vec4 uEasuCon1; // (1.0/InputWidth, 1.0/InputHeight, 0, 0)\n\nfloat lanczos2(float d) {\n    float d2 = d * d;\n    return max(0.0, (1.0 - d2) * (1.0 - d2 * 0.25));\n}\n\nfloat luma(vec3 c) {\n    return dot(c, vec3(0.2126, 0.7152, 0.0722));\n}\n\nvoid main() {\n    vec2 texelSize = uEasuCon1.xy;\n    \n    // [FIX-v1.12.0] 彻底移除 v1.9.9 中的偏移，恢复 1:1 采样对齐，消除模糊\n    vec2 sampleCoord = vTexCoord;\n    \n    vec3 cC = texture(uTexture, sampleCoord).rgb;\n    vec3 cT = texture(uTexture, clamp(sampleCoord + vec2(0.0, -texelSize.y), 0.0, 1.0)).rgb;\n    vec3 cB = texture(uTexture, clamp(sampleCoord + vec2(0.0,  texelSize.y), 0.0, 1.0)).rgb;\n    vec3 cL = texture(uTexture, clamp(sampleCoord + vec2(-texelSize.x, 0.0), 0.0, 1.0)).rgb;\n    vec3 cR = texture(uTexture, clamp(sampleCoord + vec2( texelSize.x, 0.0), 0.0, 1.0)).rgb;\n\n    float lC = luma(cC), lT = luma(cT), lB = luma(cB), lL = luma(cL), lR = luma(cR);\n    float gradH = abs(lL - lR), gradV = abs(lT - lB);\n    float edgeStrength = clamp(max(gradH, gradV) * 4.0, 0.0, 1.0);\n\n    vec3 colorEdge;\n    if (gradH > gradV) {\n        vec3 cLL = texture(uTexture, clamp(sampleCoord + vec2(-2.0 * texelSize.x, 0.0), 0.0, 1.0)).rgb;\n        vec3 cRR = texture(uTexture, clamp(sampleCoord + vec2( 2.0 * texelSize.x, 0.0), 0.0, 1.0)).rgb;\n        float w0 = lanczos2(0.0), w1 = lanczos2(1.0), w2 = lanczos2(2.0);\n        colorEdge = (cC * w0 + (cL + cR) * w1 + (cLL + cRR) * w2) / (w0 + 2.0*w1 + 2.0*w2);\n    } else {\n        vec3 cTT = texture(uTexture, clamp(sampleCoord + vec2(0.0, -2.0 * texelSize.y), 0.0, 1.0)).rgb;\n        vec3 cBB = texture(uTexture, clamp(sampleCoord + vec2(0.0,  2.0 * texelSize.y), 0.0, 1.0)).rgb;\n        float w0 = lanczos2(0.0), w1 = lanczos2(1.0), w2 = lanczos2(2.0);\n        colorEdge = (cC * w0 + (cT + cB) * w1 + (cTT + cBB) * w2) / (w0 + 2.0*w1 + 2.0*w2);\n    }\n    \n    fragColor = vec4(clamp(mix(cC, colorEdge, edgeStrength), 0.0, 1.0), 1.0);\n}\n";
    public static final String FRAG_RCAS = "#version 300 es\nprecision mediump float;\nin vec2 vTexCoord;\nout vec4 fragColor;\nuniform sampler2D uTexture;\nuniform vec4 uRcasCon; // (Sharpness, 0, 0, 0)\n\nvoid main() {\n    vec2 rcpSize = 1.0 / vec2(textureSize(uTexture, 0));\n    float sharpness = uRcasCon.x * 0.5;\n\n    vec2 sampleCoord = vTexCoord;\n    vec3 c = texture(uTexture, sampleCoord).rgb;\n    vec3 t = texture(uTexture, clamp(sampleCoord + vec2(0.0, -rcpSize.y), 0.0, 1.0)).rgb;\n    vec3 b = texture(uTexture, clamp(sampleCoord + vec2(0.0,  rcpSize.y), 0.0, 1.0)).rgb;\n    vec3 l = texture(uTexture, clamp(sampleCoord + vec2(-rcpSize.x, 0.0), 0.0, 1.0)).rgb;\n    vec3 r = texture(uTexture, clamp(sampleCoord + vec2( rcpSize.x, 0.0), 0.0, 1.0)).rgb;\n\n    float lumaC = dot(c, vec3(0.2126, 0.7152, 0.0722));\n    float lumaT = dot(t, vec3(0.2126, 0.7152, 0.0722));\n    float lumaB = dot(b, vec3(0.2126, 0.7152, 0.0722));\n    float lumaL = dot(l, vec3(0.2126, 0.7152, 0.0722));\n    float lumaR = dot(r, vec3(0.2126, 0.7152, 0.0722));\n\n    float neighborMean = (lumaT + lumaB + lumaL + lumaR) * 0.25;\n    float diff = lumaC - neighborMean;\n    float adaptiveW = sharpness * smoothstep(0.01, 0.1, abs(diff));\n    \n    vec3 sharpened = c + (c - (t + b + l + r) * 0.25) * adaptiveW;\n    fragColor = vec4(clamp(sharpened, 0.0, 1.0), 1.0);\n}\n";
    public static final String VERTEX_SHADER = "#version 300 es\nlayout(location = 0) in vec4 aPosition;\nlayout(location = 1) in vec2 aTexCoord;\nout vec2 vTexCoord;\nvoid main() {\n    gl_Position = aPosition;\n    vTexCoord = aTexCoord;\n}\n";
}
